name: Deploy to AWS S3 + CloudFront

on:
  push:
    branches:
      - main  # Deploy when pushing to main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Fetch submodules (_data, avatars)
          fetch-depth: 0  # Full history for Jekyll
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Compatible with old gem versions
          bundler-cache: false  # Disabled - no Gemfile.lock
      
      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install --jobs 4 --retry 3
      
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --verbose
        env:
          JEKYLL_ENV: production
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      
      - name: Sync to S3
        run: |
          aws s3 sync _site/ s3://${{ secrets.S3_BUCKET }}/${{ github.event.repository.name }}/ \
            --delete \
            --cache-control "public, max-age=300" \
            --exclude ".git/*" \
            --exclude ".github/*"
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DIST_ID }} \
            --paths "/${{ github.event.repository.name }}/*"
      
      - name: Deployment summary
        run: |
          echo "✅ Deployment complete!"
          echo "Repository: ${{ github.event.repository.name }}"
          echo "S3 Path: s3://${{ secrets.S3_BUCKET }}/${{ github.event.repository.name }}/"
          echo "CloudFront URL: https://d101lr0mb7xh5s.cloudfront.net/${{ github.event.repository.name }}/"

